name: PR Check

on:
  pull:
    branches: [main]

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: PR branch name
        uses: echo "PR check running for branch is ${{ github.head_ref }}"

