name: hello

on:
  push:
    branches: [main]

  schedule:
    - corn: "0 0 * * *"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code using actions/checkout
        uses: actions/checkout@v4

      - name: Print hello
        run: echo "Hello from GitHub Actions!" 
      
      - name: current date and time
        run: date "+%Y-%m-%d %H:%M:%S"
      
      - name: branch name
        run: echo "name of branch that triggered the run is ${{ github.ref_name }}"
      
      - name: list of files
        run: ls -a
      
      - name: runner's operating system
        run: uname -a 