name: manual trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enter environment (staging/production)'
        required: true
        options:
          - staging
          - production

jobs:
  input-value:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment input
        run: echo "Selected environment is ${{github.event.inputs.environment}}"