name: PR Check

on:
  workflow_dispatch: 

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR branch name
        uses: echo "PR check running for branch is ${{ github.head_ref }}"

