name: PR Check

on:
  pull_request:
    branches: [main]

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR branch name
        run: echo "PR check running for branch is ${{ github.head_ref }}"