name: Secret reading 

on:
  workflow_dispatch:

jobs:
  Secret-scan:
    runs-on: ubuntu-latest
    steps:
      -name: Checking secret message
      run: |
        if [ -n "${{ secrets.SECRET_NAME }}" ]; then
          echo "The secret is set: true"
        else
          echo "The secret is set: false"
      
      - name: print secret message
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}"